disabled_rules:
  - trailing_whitespace
  - line_length
  - comment_spacing

opt_in_rules:
  - empty_count
  - first_where
  - force_unwrapping
  - fatal_error_message
  - sorted_imports

included:
  - audiory
  - audioryTests
  - audioryUITests

excluded:
  - Carthage
  - Pods
  - .build

identifier_name:
  allowed_symbols: "_"
  min_length: 3
  max_length: 60
  validates_start_with_lowercase: false

type_name:
  min_length: 3
  max_length: 60

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 80
  error: 200

cyclomatic_complexity:
  ignores_case_statements: true

reporter: "xcode"

